// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: user/userService.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	GetRequest(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetAllRequest(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*UsersResponse, error)
	PostRequest(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*GetResponse, error)
	PostAdminRequest(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*GetResponse, error)
	UpdateRequest(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*GetResponse, error)
	DeleteRequest(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*EmptyRequest, error)
	SearchUsersRequest(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*UsersResponse, error)
	LoginRequest(ctx context.Context, in *CredentialsRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	ConfirmRegistration(ctx context.Context, in *ConfirmationRequest, opts ...grpc.CallOption) (*ConfirmationResponse, error)
	IsUserAuthenticated(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	IsApiTokenValid(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*UserIdRequest, error)
	GetQR2FA(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*TFAResponse, error)
	Enable2FA(ctx context.Context, in *TFARequest, opts ...grpc.CallOption) (*EmptyRequest, error)
	Verify2FA(ctx context.Context, in *TFARequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Disable2FA(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*EmptyRequest, error)
	UpdatePasswordRequest(ctx context.Context, in *NewPasswordRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetAllUsersExperienceRequest(ctx context.Context, in *ExperienceRequest, opts ...grpc.CallOption) (*ExperienceResponse, error)
	PostExperienceRequest(ctx context.Context, in *NewExperienceRequest, opts ...grpc.CallOption) (*NewExperienceResponse, error)
	DeleteExperienceRequest(ctx context.Context, in *DeleteUsersExperienceRequest, opts ...grpc.CallOption) (*EmptyRequest, error)
	IsUserPrivateRequest(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*PrivateResponse, error)
	AddUserSkill(ctx context.Context, in *NewSkillRequest, opts ...grpc.CallOption) (*EmptyRequest, error)
	AddUserInterest(ctx context.Context, in *NewInterestRequest, opts ...grpc.CallOption) (*EmptyRequest, error)
	RemoveSkill(ctx context.Context, in *RemoveSkillRequest, opts ...grpc.CallOption) (*EmptyRequest, error)
	RemoveInterest(ctx context.Context, in *RemoveInterestRequest, opts ...grpc.CallOption) (*EmptyRequest, error)
	ApiTokenRequest(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*ApiTokenResponse, error)
	ApiTokenCreateRequest(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*ApiTokenResponse, error)
	ApiTokenRemoveRequest(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*EmptyRequest, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetRequest(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAllRequest(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*UsersResponse, error) {
	out := new(UsersResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetAllRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) PostRequest(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/PostRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) PostAdminRequest(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/PostAdminRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateRequest(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/UpdateRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteRequest(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*EmptyRequest, error) {
	out := new(EmptyRequest)
	err := c.cc.Invoke(ctx, "/user.UserService/DeleteRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SearchUsersRequest(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*UsersResponse, error) {
	out := new(UsersResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/SearchUsersRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LoginRequest(ctx context.Context, in *CredentialsRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/LoginRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ConfirmRegistration(ctx context.Context, in *ConfirmationRequest, opts ...grpc.CallOption) (*ConfirmationResponse, error) {
	out := new(ConfirmationResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/ConfirmRegistration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) IsUserAuthenticated(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/IsUserAuthenticated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) IsApiTokenValid(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*UserIdRequest, error) {
	out := new(UserIdRequest)
	err := c.cc.Invoke(ctx, "/user.UserService/IsApiTokenValid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetQR2FA(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*TFAResponse, error) {
	out := new(TFAResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetQR2FA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Enable2FA(ctx context.Context, in *TFARequest, opts ...grpc.CallOption) (*EmptyRequest, error) {
	out := new(EmptyRequest)
	err := c.cc.Invoke(ctx, "/user.UserService/Enable2FA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Verify2FA(ctx context.Context, in *TFARequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/Verify2FA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Disable2FA(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*EmptyRequest, error) {
	out := new(EmptyRequest)
	err := c.cc.Invoke(ctx, "/user.UserService/Disable2FA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdatePasswordRequest(ctx context.Context, in *NewPasswordRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/UpdatePasswordRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAllUsersExperienceRequest(ctx context.Context, in *ExperienceRequest, opts ...grpc.CallOption) (*ExperienceResponse, error) {
	out := new(ExperienceResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetAllUsersExperienceRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) PostExperienceRequest(ctx context.Context, in *NewExperienceRequest, opts ...grpc.CallOption) (*NewExperienceResponse, error) {
	out := new(NewExperienceResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/PostExperienceRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteExperienceRequest(ctx context.Context, in *DeleteUsersExperienceRequest, opts ...grpc.CallOption) (*EmptyRequest, error) {
	out := new(EmptyRequest)
	err := c.cc.Invoke(ctx, "/user.UserService/DeleteExperienceRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) IsUserPrivateRequest(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*PrivateResponse, error) {
	out := new(PrivateResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/IsUserPrivateRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddUserSkill(ctx context.Context, in *NewSkillRequest, opts ...grpc.CallOption) (*EmptyRequest, error) {
	out := new(EmptyRequest)
	err := c.cc.Invoke(ctx, "/user.UserService/AddUserSkill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddUserInterest(ctx context.Context, in *NewInterestRequest, opts ...grpc.CallOption) (*EmptyRequest, error) {
	out := new(EmptyRequest)
	err := c.cc.Invoke(ctx, "/user.UserService/AddUserInterest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RemoveSkill(ctx context.Context, in *RemoveSkillRequest, opts ...grpc.CallOption) (*EmptyRequest, error) {
	out := new(EmptyRequest)
	err := c.cc.Invoke(ctx, "/user.UserService/RemoveSkill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RemoveInterest(ctx context.Context, in *RemoveInterestRequest, opts ...grpc.CallOption) (*EmptyRequest, error) {
	out := new(EmptyRequest)
	err := c.cc.Invoke(ctx, "/user.UserService/RemoveInterest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ApiTokenRequest(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*ApiTokenResponse, error) {
	out := new(ApiTokenResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/ApiTokenRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ApiTokenCreateRequest(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*ApiTokenResponse, error) {
	out := new(ApiTokenResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/ApiTokenCreateRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ApiTokenRemoveRequest(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*EmptyRequest, error) {
	out := new(EmptyRequest)
	err := c.cc.Invoke(ctx, "/user.UserService/ApiTokenRemoveRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	GetRequest(context.Context, *UserIdRequest) (*GetResponse, error)
	GetAllRequest(context.Context, *EmptyRequest) (*UsersResponse, error)
	PostRequest(context.Context, *UserRequest) (*GetResponse, error)
	PostAdminRequest(context.Context, *UserRequest) (*GetResponse, error)
	UpdateRequest(context.Context, *UserRequest) (*GetResponse, error)
	DeleteRequest(context.Context, *UserIdRequest) (*EmptyRequest, error)
	SearchUsersRequest(context.Context, *SearchRequest) (*UsersResponse, error)
	LoginRequest(context.Context, *CredentialsRequest) (*LoginResponse, error)
	ConfirmRegistration(context.Context, *ConfirmationRequest) (*ConfirmationResponse, error)
	IsUserAuthenticated(context.Context, *AuthRequest) (*AuthResponse, error)
	IsApiTokenValid(context.Context, *AuthRequest) (*UserIdRequest, error)
	GetQR2FA(context.Context, *UserIdRequest) (*TFAResponse, error)
	Enable2FA(context.Context, *TFARequest) (*EmptyRequest, error)
	Verify2FA(context.Context, *TFARequest) (*LoginResponse, error)
	Disable2FA(context.Context, *UserIdRequest) (*EmptyRequest, error)
	UpdatePasswordRequest(context.Context, *NewPasswordRequest) (*GetResponse, error)
	GetAllUsersExperienceRequest(context.Context, *ExperienceRequest) (*ExperienceResponse, error)
	PostExperienceRequest(context.Context, *NewExperienceRequest) (*NewExperienceResponse, error)
	DeleteExperienceRequest(context.Context, *DeleteUsersExperienceRequest) (*EmptyRequest, error)
	IsUserPrivateRequest(context.Context, *UserIdRequest) (*PrivateResponse, error)
	AddUserSkill(context.Context, *NewSkillRequest) (*EmptyRequest, error)
	AddUserInterest(context.Context, *NewInterestRequest) (*EmptyRequest, error)
	RemoveSkill(context.Context, *RemoveSkillRequest) (*EmptyRequest, error)
	RemoveInterest(context.Context, *RemoveInterestRequest) (*EmptyRequest, error)
	ApiTokenRequest(context.Context, *UserIdRequest) (*ApiTokenResponse, error)
	ApiTokenCreateRequest(context.Context, *UserIdRequest) (*ApiTokenResponse, error)
	ApiTokenRemoveRequest(context.Context, *UserIdRequest) (*EmptyRequest, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) GetRequest(context.Context, *UserIdRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequest not implemented")
}
func (UnimplementedUserServiceServer) GetAllRequest(context.Context, *EmptyRequest) (*UsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRequest not implemented")
}
func (UnimplementedUserServiceServer) PostRequest(context.Context, *UserRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostRequest not implemented")
}
func (UnimplementedUserServiceServer) PostAdminRequest(context.Context, *UserRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostAdminRequest not implemented")
}
func (UnimplementedUserServiceServer) UpdateRequest(context.Context, *UserRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRequest not implemented")
}
func (UnimplementedUserServiceServer) DeleteRequest(context.Context, *UserIdRequest) (*EmptyRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRequest not implemented")
}
func (UnimplementedUserServiceServer) SearchUsersRequest(context.Context, *SearchRequest) (*UsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUsersRequest not implemented")
}
func (UnimplementedUserServiceServer) LoginRequest(context.Context, *CredentialsRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginRequest not implemented")
}
func (UnimplementedUserServiceServer) ConfirmRegistration(context.Context, *ConfirmationRequest) (*ConfirmationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmRegistration not implemented")
}
func (UnimplementedUserServiceServer) IsUserAuthenticated(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsUserAuthenticated not implemented")
}
func (UnimplementedUserServiceServer) IsApiTokenValid(context.Context, *AuthRequest) (*UserIdRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsApiTokenValid not implemented")
}
func (UnimplementedUserServiceServer) GetQR2FA(context.Context, *UserIdRequest) (*TFAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQR2FA not implemented")
}
func (UnimplementedUserServiceServer) Enable2FA(context.Context, *TFARequest) (*EmptyRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enable2FA not implemented")
}
func (UnimplementedUserServiceServer) Verify2FA(context.Context, *TFARequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify2FA not implemented")
}
func (UnimplementedUserServiceServer) Disable2FA(context.Context, *UserIdRequest) (*EmptyRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disable2FA not implemented")
}
func (UnimplementedUserServiceServer) UpdatePasswordRequest(context.Context, *NewPasswordRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePasswordRequest not implemented")
}
func (UnimplementedUserServiceServer) GetAllUsersExperienceRequest(context.Context, *ExperienceRequest) (*ExperienceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUsersExperienceRequest not implemented")
}
func (UnimplementedUserServiceServer) PostExperienceRequest(context.Context, *NewExperienceRequest) (*NewExperienceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostExperienceRequest not implemented")
}
func (UnimplementedUserServiceServer) DeleteExperienceRequest(context.Context, *DeleteUsersExperienceRequest) (*EmptyRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExperienceRequest not implemented")
}
func (UnimplementedUserServiceServer) IsUserPrivateRequest(context.Context, *UserIdRequest) (*PrivateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsUserPrivateRequest not implemented")
}
func (UnimplementedUserServiceServer) AddUserSkill(context.Context, *NewSkillRequest) (*EmptyRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserSkill not implemented")
}
func (UnimplementedUserServiceServer) AddUserInterest(context.Context, *NewInterestRequest) (*EmptyRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserInterest not implemented")
}
func (UnimplementedUserServiceServer) RemoveSkill(context.Context, *RemoveSkillRequest) (*EmptyRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSkill not implemented")
}
func (UnimplementedUserServiceServer) RemoveInterest(context.Context, *RemoveInterestRequest) (*EmptyRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveInterest not implemented")
}
func (UnimplementedUserServiceServer) ApiTokenRequest(context.Context, *UserIdRequest) (*ApiTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApiTokenRequest not implemented")
}
func (UnimplementedUserServiceServer) ApiTokenCreateRequest(context.Context, *UserIdRequest) (*ApiTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApiTokenCreateRequest not implemented")
}
func (UnimplementedUserServiceServer) ApiTokenRemoveRequest(context.Context, *UserIdRequest) (*EmptyRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApiTokenRemoveRequest not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetRequest(ctx, req.(*UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetAllRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAllRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetAllRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAllRequest(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_PostRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).PostRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/PostRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).PostRequest(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_PostAdminRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).PostAdminRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/PostAdminRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).PostAdminRequest(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UpdateRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateRequest(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/DeleteRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteRequest(ctx, req.(*UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SearchUsersRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SearchUsersRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/SearchUsersRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SearchUsersRequest(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LoginRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LoginRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/LoginRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LoginRequest(ctx, req.(*CredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ConfirmRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ConfirmRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ConfirmRegistration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ConfirmRegistration(ctx, req.(*ConfirmationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_IsUserAuthenticated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).IsUserAuthenticated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/IsUserAuthenticated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).IsUserAuthenticated(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_IsApiTokenValid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).IsApiTokenValid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/IsApiTokenValid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).IsApiTokenValid(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetQR2FA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetQR2FA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetQR2FA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetQR2FA(ctx, req.(*UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Enable2FA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TFARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Enable2FA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Enable2FA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Enable2FA(ctx, req.(*TFARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Verify2FA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TFARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Verify2FA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Verify2FA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Verify2FA(ctx, req.(*TFARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Disable2FA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Disable2FA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Disable2FA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Disable2FA(ctx, req.(*UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdatePasswordRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdatePasswordRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UpdatePasswordRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdatePasswordRequest(ctx, req.(*NewPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetAllUsersExperienceRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExperienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAllUsersExperienceRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetAllUsersExperienceRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAllUsersExperienceRequest(ctx, req.(*ExperienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_PostExperienceRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewExperienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).PostExperienceRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/PostExperienceRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).PostExperienceRequest(ctx, req.(*NewExperienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteExperienceRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUsersExperienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteExperienceRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/DeleteExperienceRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteExperienceRequest(ctx, req.(*DeleteUsersExperienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_IsUserPrivateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).IsUserPrivateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/IsUserPrivateRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).IsUserPrivateRequest(ctx, req.(*UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AddUserSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddUserSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/AddUserSkill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddUserSkill(ctx, req.(*NewSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AddUserInterest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewInterestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddUserInterest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/AddUserInterest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddUserInterest(ctx, req.(*NewInterestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RemoveSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RemoveSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/RemoveSkill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RemoveSkill(ctx, req.(*RemoveSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RemoveInterest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveInterestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RemoveInterest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/RemoveInterest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RemoveInterest(ctx, req.(*RemoveInterestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ApiTokenRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ApiTokenRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ApiTokenRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ApiTokenRequest(ctx, req.(*UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ApiTokenCreateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ApiTokenCreateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ApiTokenCreateRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ApiTokenCreateRequest(ctx, req.(*UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ApiTokenRemoveRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ApiTokenRemoveRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ApiTokenRemoveRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ApiTokenRemoveRequest(ctx, req.(*UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRequest",
			Handler:    _UserService_GetRequest_Handler,
		},
		{
			MethodName: "GetAllRequest",
			Handler:    _UserService_GetAllRequest_Handler,
		},
		{
			MethodName: "PostRequest",
			Handler:    _UserService_PostRequest_Handler,
		},
		{
			MethodName: "PostAdminRequest",
			Handler:    _UserService_PostAdminRequest_Handler,
		},
		{
			MethodName: "UpdateRequest",
			Handler:    _UserService_UpdateRequest_Handler,
		},
		{
			MethodName: "DeleteRequest",
			Handler:    _UserService_DeleteRequest_Handler,
		},
		{
			MethodName: "SearchUsersRequest",
			Handler:    _UserService_SearchUsersRequest_Handler,
		},
		{
			MethodName: "LoginRequest",
			Handler:    _UserService_LoginRequest_Handler,
		},
		{
			MethodName: "ConfirmRegistration",
			Handler:    _UserService_ConfirmRegistration_Handler,
		},
		{
			MethodName: "IsUserAuthenticated",
			Handler:    _UserService_IsUserAuthenticated_Handler,
		},
		{
			MethodName: "IsApiTokenValid",
			Handler:    _UserService_IsApiTokenValid_Handler,
		},
		{
			MethodName: "GetQR2FA",
			Handler:    _UserService_GetQR2FA_Handler,
		},
		{
			MethodName: "Enable2FA",
			Handler:    _UserService_Enable2FA_Handler,
		},
		{
			MethodName: "Verify2FA",
			Handler:    _UserService_Verify2FA_Handler,
		},
		{
			MethodName: "Disable2FA",
			Handler:    _UserService_Disable2FA_Handler,
		},
		{
			MethodName: "UpdatePasswordRequest",
			Handler:    _UserService_UpdatePasswordRequest_Handler,
		},
		{
			MethodName: "GetAllUsersExperienceRequest",
			Handler:    _UserService_GetAllUsersExperienceRequest_Handler,
		},
		{
			MethodName: "PostExperienceRequest",
			Handler:    _UserService_PostExperienceRequest_Handler,
		},
		{
			MethodName: "DeleteExperienceRequest",
			Handler:    _UserService_DeleteExperienceRequest_Handler,
		},
		{
			MethodName: "IsUserPrivateRequest",
			Handler:    _UserService_IsUserPrivateRequest_Handler,
		},
		{
			MethodName: "AddUserSkill",
			Handler:    _UserService_AddUserSkill_Handler,
		},
		{
			MethodName: "AddUserInterest",
			Handler:    _UserService_AddUserInterest_Handler,
		},
		{
			MethodName: "RemoveSkill",
			Handler:    _UserService_RemoveSkill_Handler,
		},
		{
			MethodName: "RemoveInterest",
			Handler:    _UserService_RemoveInterest_Handler,
		},
		{
			MethodName: "ApiTokenRequest",
			Handler:    _UserService_ApiTokenRequest_Handler,
		},
		{
			MethodName: "ApiTokenCreateRequest",
			Handler:    _UserService_ApiTokenCreateRequest_Handler,
		},
		{
			MethodName: "ApiTokenRemoveRequest",
			Handler:    _UserService_ApiTokenRemoveRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/userService.proto",
}
